package com.topview.dao;

import com.topview.domain.Electrician;

public interface ElectricianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int deleteByPrimaryKey(String mobilephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int insert(Electrician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int insertSelective(Electrician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    Electrician selectByPrimaryKey(String mobilephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int updateByPrimaryKeySelective(Electrician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int updateByPrimaryKey(Electrician record);
}