package com.topview.dao;

import com.topview.domain.TransactionRecord;

public interface TransactionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int deleteByPrimaryKey(String transactionRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int insert(TransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int insertSelective(TransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    TransactionRecord selectByPrimaryKey(String transactionRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int updateByPrimaryKeySelective(TransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int updateByPrimaryKey(TransactionRecord record);
}