package com.topview.dao;

import com.topview.domain.WalletChangeLog;

public interface WalletChangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_change_log
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int deleteByPrimaryKey(String walletChangeLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_change_log
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int insert(WalletChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_change_log
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int insertSelective(WalletChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_change_log
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    WalletChangeLog selectByPrimaryKey(String walletChangeLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_change_log
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int updateByPrimaryKeySelective(WalletChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wallet_change_log
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    int updateByPrimaryKey(WalletChangeLog record);
}