package com.topview.domain;

public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.mobliephone
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String mobliephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.username
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.password
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.security_question
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String securityQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.security_answer
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String securityAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.real_name
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private Boolean realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.identity_card_front
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String identityCardFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.identity_card_back
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String identityCardBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.identity_card
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.identity_card_secret
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String identityCardSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.salt
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.mobliephone
     *
     * @return the value of client.mobliephone
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getMobliephone() {
        return mobliephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.mobliephone
     *
     * @param mobliephone the value for client.mobliephone
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setMobliephone(String mobliephone) {
        this.mobliephone = mobliephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.username
     *
     * @return the value of client.username
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.username
     *
     * @param username the value for client.username
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.password
     *
     * @return the value of client.password
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.password
     *
     * @param password the value for client.password
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.security_question
     *
     * @return the value of client.security_question
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getSecurityQuestion() {
        return securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.security_question
     *
     * @param securityQuestion the value for client.security_question
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.security_answer
     *
     * @return the value of client.security_answer
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getSecurityAnswer() {
        return securityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.security_answer
     *
     * @param securityAnswer the value for client.security_answer
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setSecurityAnswer(String securityAnswer) {
        this.securityAnswer = securityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.real_name
     *
     * @return the value of client.real_name
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public Boolean getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.real_name
     *
     * @param realName the value for client.real_name
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setRealName(Boolean realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.identity_card_front
     *
     * @return the value of client.identity_card_front
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getIdentityCardFront() {
        return identityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.identity_card_front
     *
     * @param identityCardFront the value for client.identity_card_front
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setIdentityCardFront(String identityCardFront) {
        this.identityCardFront = identityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.identity_card_back
     *
     * @return the value of client.identity_card_back
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getIdentityCardBack() {
        return identityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.identity_card_back
     *
     * @param identityCardBack the value for client.identity_card_back
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setIdentityCardBack(String identityCardBack) {
        this.identityCardBack = identityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.identity_card
     *
     * @return the value of client.identity_card
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.identity_card
     *
     * @param identityCard the value for client.identity_card
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.identity_card_secret
     *
     * @return the value of client.identity_card_secret
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getIdentityCardSecret() {
        return identityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.identity_card_secret
     *
     * @param identityCardSecret the value for client.identity_card_secret
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setIdentityCardSecret(String identityCardSecret) {
        this.identityCardSecret = identityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.salt
     *
     * @return the value of client.salt
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.salt
     *
     * @param salt the value for client.salt
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }
}