package com.topview.domain;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.title
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.content
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.pic
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.video
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.type
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private Boolean type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.title
     *
     * @return the value of course.title
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.title
     *
     * @param title the value for course.title
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.content
     *
     * @return the value of course.content
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.content
     *
     * @param content the value for course.content
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.pic
     *
     * @return the value of course.pic
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.pic
     *
     * @param pic the value for course.pic
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.video
     *
     * @return the value of course.video
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.video
     *
     * @param video the value for course.video
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setVideo(String video) {
        this.video = video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type
     *
     * @return the value of course.type
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type
     *
     * @param type the value for course.type
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setType(Boolean type) {
        this.type = type;
    }
}