package com.topview.domain;

public class Electrician {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.mobilephone
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.username
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.password
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.security_question
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String securityQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.security_answer
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String securityAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.address
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.real_name
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private Boolean realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card_front
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String legalPersonIdentityCardFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card_back
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String legalPersonIdentityCardBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String legalPersonIdentityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card_secret
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String legalPersonIdentityCardSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.salt
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.type
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.business_license
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String businessLicense;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.mobilephone
     *
     * @return the value of electrician.mobilephone
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.mobilephone
     *
     * @param mobilephone the value for electrician.mobilephone
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.username
     *
     * @return the value of electrician.username
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.username
     *
     * @param username the value for electrician.username
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.password
     *
     * @return the value of electrician.password
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.password
     *
     * @param password the value for electrician.password
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.security_question
     *
     * @return the value of electrician.security_question
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getSecurityQuestion() {
        return securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.security_question
     *
     * @param securityQuestion the value for electrician.security_question
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.security_answer
     *
     * @return the value of electrician.security_answer
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getSecurityAnswer() {
        return securityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.security_answer
     *
     * @param securityAnswer the value for electrician.security_answer
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setSecurityAnswer(String securityAnswer) {
        this.securityAnswer = securityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.address
     *
     * @return the value of electrician.address
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.address
     *
     * @param address the value for electrician.address
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.real_name
     *
     * @return the value of electrician.real_name
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public Boolean getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.real_name
     *
     * @param realName the value for electrician.real_name
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setRealName(Boolean realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card_front
     *
     * @return the value of electrician.legal_person_identity_card_front
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getLegalPersonIdentityCardFront() {
        return legalPersonIdentityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card_front
     *
     * @param legalPersonIdentityCardFront the value for electrician.legal_person_identity_card_front
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setLegalPersonIdentityCardFront(String legalPersonIdentityCardFront) {
        this.legalPersonIdentityCardFront = legalPersonIdentityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card_back
     *
     * @return the value of electrician.legal_person_identity_card_back
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getLegalPersonIdentityCardBack() {
        return legalPersonIdentityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card_back
     *
     * @param legalPersonIdentityCardBack the value for electrician.legal_person_identity_card_back
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setLegalPersonIdentityCardBack(String legalPersonIdentityCardBack) {
        this.legalPersonIdentityCardBack = legalPersonIdentityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card
     *
     * @return the value of electrician.legal_person_identity_card
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getLegalPersonIdentityCard() {
        return legalPersonIdentityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card
     *
     * @param legalPersonIdentityCard the value for electrician.legal_person_identity_card
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setLegalPersonIdentityCard(String legalPersonIdentityCard) {
        this.legalPersonIdentityCard = legalPersonIdentityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card_secret
     *
     * @return the value of electrician.legal_person_identity_card_secret
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getLegalPersonIdentityCardSecret() {
        return legalPersonIdentityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card_secret
     *
     * @param legalPersonIdentityCardSecret the value for electrician.legal_person_identity_card_secret
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setLegalPersonIdentityCardSecret(String legalPersonIdentityCardSecret) {
        this.legalPersonIdentityCardSecret = legalPersonIdentityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.salt
     *
     * @return the value of electrician.salt
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.salt
     *
     * @param salt the value for electrician.salt
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.type
     *
     * @return the value of electrician.type
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.type
     *
     * @param type the value for electrician.type
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.business_license
     *
     * @return the value of electrician.business_license
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.business_license
     *
     * @param businessLicense the value for electrician.business_license
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense;
    }
}