package com.topview.domain;

public class Evaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate. evaluate_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String evaluateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.content
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.pic
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.star_level
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private Integer starLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.score
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.work_order_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String workOrderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate. evaluate_id
     *
     * @return the value of evaluate. evaluate_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getEvaluateId() {
        return evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate. evaluate_id
     *
     * @param evaluateId the value for evaluate. evaluate_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setEvaluateId(String evaluateId) {
        this.evaluateId = evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.content
     *
     * @return the value of evaluate.content
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.content
     *
     * @param content the value for evaluate.content
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.pic
     *
     * @return the value of evaluate.pic
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.pic
     *
     * @param pic the value for evaluate.pic
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.star_level
     *
     * @return the value of evaluate.star_level
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public Integer getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.star_level
     *
     * @param starLevel the value for evaluate.star_level
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setStarLevel(Integer starLevel) {
        this.starLevel = starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.score
     *
     * @return the value of evaluate.score
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.score
     *
     * @param score the value for evaluate.score
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.work_order_id
     *
     * @return the value of evaluate.work_order_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getWorkOrderId() {
        return workOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.work_order_id
     *
     * @param workOrderId the value for evaluate.work_order_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setWorkOrderId(String workOrderId) {
        this.workOrderId = workOrderId;
    }
}