package com.topview.domain;

public class EWallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.e_wallet_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String eWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.balance
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.user_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.e_wallet_id
     *
     * @return the value of e_wallet.e_wallet_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String geteWalletId() {
        return eWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.e_wallet_id
     *
     * @param eWalletId the value for e_wallet.e_wallet_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void seteWalletId(String eWalletId) {
        this.eWalletId = eWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.balance
     *
     * @return the value of e_wallet.balance
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.balance
     *
     * @param balance the value for e_wallet.balance
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.user_id
     *
     * @return the value of e_wallet.user_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.user_id
     *
     * @param userId the value for e_wallet.user_id
     *
     * @mbggenerated Mon Jan 22 00:11:46 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}